<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ItemparamSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('itemparams')->insert([
            [
                'groupid' => 21,
                'param_name' => 'Processzor foglalat',
                'value' => 'LGA 1700',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Processzor foglalat',
                'value' => 'Socket AM4',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Alaplap méret',
                'value' => 'microATX',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Chip készlet',
                'value' => 'Intel® B760',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Memória típusa',
                'value' => 'DDR4',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Memória architektúra',
                'value' => 'Dual Channel',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Memória foglalat száma',
                'value' => '2 db',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Memória maximális órajele',
                'value' => '5333 MHz',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Memória maximális mérete',
                'value' => '64 GB',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Bővítőhelyek PCIe 4.0 x16',
                'value' => '1 db',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Bővítőhelyek PCIe 4.0 x1',
                'value' => '2 db',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Háttértár csatlakozó M.2',
                'value' => '2 db',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Háttértár csatlakozó SATAIII',
                'value' => '4 db',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Maximum M.2 adatátviteli mód',
                'value' => 'NVMe (PCIe x4)',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'RAID támogatás',
                'value' => 'igen',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Hátlapi USB-A 3.2 Gen 1',
                'value' => '4 db',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Hátlapi USB 2.0',
                'value' => '2 db',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Hátlapi HDMI',
                'value' => '1 db',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Hátlapi D-sub',
                'value' => '1 db',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Hátlapi PS/2',
                'value' => '1 db',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Hátlapi audió',
                'value' => '3 db',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Audio jack',
                'value' => 'igen',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Audio codec típusa',
                'value' => 'Realtek 7.1 Surround Sound',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Integrált LAN típusa',
                'value' => 'Realtek 2.5GbE LAN chip',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Alaplap méret',
                'value' => 'ATX',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Chip készlet',
                'value' => 'AMD B550',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Memória foglalat száma',
                'value' => '4 db',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Memória maximális órajele',
                'value' => '4600 MHz',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Memória maximális mérete',
                'value' => '128 GB',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Bővítőhelyek PCIe 3.0 x16',
                'value' => '1 db',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Bővítőhelyek PCIe 3.0 x1',
                'value' => '3 db',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Hátlapi USB-C 3.2 Gen2',
                'value' => '1 db',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Hátlapi USB-A 3.2 Gen 2',
                'value' => '1 db',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Maximális operációs memória frekvencia',
                'value' => '4800 MHz',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Serial ATA III csatlakozók',
                'value' => '6 db',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Hátlapi audió',
                'value' => 'Audio jack + Optical S/PDIF out',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Audio codec típusa',
                'value' => 'SupremeFX',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Integrált LAN típusa',
                'value' => 'Intel I225-V 2.5Gb',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Chip készlet',
                'value' => 'AMD A520',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Háttértár csatlakozó M.2',
                'value' => '1 db',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Maximum M.2 adatátviteli mód',
                'value' => 'SATA és NVMe',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 21,
                'param_name' => 'Csatlakozó típusa',
                'value' => 'PCIe 4.0',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 22,
                'param_name' => 'Grafikus processzor típusa',
                'value' => 'GeForce RTX 4060',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 22,
                'param_name' => 'GPU turbó órajele',
                'value' => '2535 MHz',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 22,
                'param_name' => 'Memória mérete',
                'value' => '8 GB',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 22,
                'param_name' => 'Memória Interfész',
                'value' => '128 bit',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 22,
                'param_name' => 'Memória típusa',
                'value' => 'GDDR6',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 22,
                'param_name' => 'Memória sebessége',
                'value' => '17 Gbps',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 22,
                'param_name' => 'DisplayPort',
                'value' => '3 db',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 22,
                'param_name' => 'HDMI',
                'value' => '1 db',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 22,
                'param_name' => 'Maximális felbontás',
                'value' => '7680 x 4320 pixel',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 22,
                'param_name' => 'DirectX támogatás',
                'value' => 'DirectX 12',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 22,
                'param_name' => 'Csatlakozó típusa',
                'value' => 'PCIe 5.0',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 22,
                'param_name' => 'Grafikus processzor típusa',
                'value' => 'NVIDIA® GeForce RTX™ 5070',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 22,
                'param_name' => 'Memória mérete',
                'value' => '12 GB',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 22,
                'param_name' => 'Memória Interfész',
                'value' => '192 bit',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 22,
                'param_name' => 'Memória típusa',
                'value' => 'GDDR7',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 22,
                'param_name' => 'Memória sebessége',
                'value' => '28 Gbps',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 22,
                'param_name' => 'HDMI',
                'value' => '2 db',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 22,
                'param_name' => 'Grafikus processzor gyártója',
                'value' => 'AMD',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 22,
                'param_name' => 'Grafikus processzor modell',
                'value' => 'Radeon RX 7800 XT',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 22,
                'param_name' => 'GPU órajel',
                'value' => '2254 MHz',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 22,
                'param_name' => 'GPU Boost órajel',
                'value' => '2565 MHz',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 22,
                'param_name' => 'Memória sávszélesség',
                'value' => '624 GB/s',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 22,
                'param_name' => 'Ajánlott tápegység',
                'value' => '700 W',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 22,
                'param_name' => 'Táp csatlakozó',
                'value' => '2x8 pin',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 22,
                'param_name' => 'Hűtés típusa',
                'value' => 'Aktív',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 22,
                'param_name' => 'Foglalat',
                'value' => 'PCI-E 4.0',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 22,
                'param_name' => 'GPU órajele',
                'value' => '2460 MHz',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 22,
                'param_name' => 'DisplayPort',
                'value' => '2 db',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Képátló (inch)',
                'value' => '34',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Panel típusa',
                'value' => 'VA',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Maximális felbontás',
                'value' => '3440 x 1440 pixel',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'HDMI',
                'value' => 'igen',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'DisplayPort',
                'value' => 'igen',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Képfrissítési frekvencia',
                'value' => '165 Hz',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Fényerő (cd/m2)',
                'value' => '250',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Képarány',
                'value' => '21:9 Wide képarány',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Válaszidő (ms)',
                'value' => '1',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Ívelt kijelző',
                'value' => 'igen',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Kontraszt arány',
                'value' => '2 500:1',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Falra szerelhető',
                'value' => 'igen',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Falra szerelhető, szabvány',
                'value' => '75 x 75 mm',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Falra szerelhető, szabvány',
                'value' => 'VESA: 100x100mm',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Szélesség',
                'value' => '807 mm',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Szélesség',
                'value' => '536 mm',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Maximális magasság',
                'value' => '476 mm',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Maximális magasság',
                'value' => '413 mm',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Vastagság',
                'value' => '273 mm',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Vastagság',
                'value' => '202 mm',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Energiaosztály',
                'value' => 'G',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Energiaosztály',
                'value' => 'F',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Gamer',
                'value' => 'Igen',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Képátló (inch)',
                'value' => '24',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Panel típusa',
                'value' => 'VA',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Maximális felbontás',
                'value' => '1920 x 1080 pixel',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'D-SUB',
                'value' => 'igen',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'HDMI',
                'value' => 'igen',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Képfrissítési frekvencia',
                'value' => '100 Hz',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Látószög H/V',
                'value' => '178°/178°',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Fényerő (cd/m2)',
                'value' => '250',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Képarány',
                'value' => '16:9 Wide képarány',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Válaszidő (ms)',
                'value' => '4',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Kontraszt arány',
                'value' => '3 000:1',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Szélesség',
                'value' => '547.8 mm',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Maximális magasság',
                'value' => '416.3 mm',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Vastagság',
                'value' => '214 mm',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
            [
                'groupid' => 23,
                'param_name' => 'Energiaosztály',
                'value' => 'E',
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
            ],
        ]);
    }
}
