<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            [
                'groupId' => 21,
                'brandId' => 5,
                'barcode' => '1234567890123',
                'name' => 'PRIME B760M-K D4',
                'parameter_ids' => '1,3,4,5,6,7',
                'description' => '',
                'status' => 'active',
                'price' => 37600.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'groupId' => 21,
                'brandId' => 5,
                'barcode' => '1234567890124',
                'name' => 'ROG STRIX B550-F GAMING',
                'website' => 'https://rog.asus.com/motherboards/rog-strix/rog-strix-b550-f-gaming-model/',
                'parameter_ids' => '24,25,4,5,28',
                'description' => '',
                'status' => 'active',
                'price' => 55790.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'groupId' => 21,
                'brandId' => 6,
                'barcode' => '1234567890125',
                'name' => 'B550-A PRO',
                'parameter_ids' => '',
                'description' => '',
                'status' => 'active',
                'price' => 46890.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'groupId' => 21,
                'brandId' => 6,
                'barcode' => '1234567890126',
                'name' => 'A520M PRO',
                'parameter_ids' => '2,3,39,5,6',
                'description' => '',
                'status' => 'active',
                'price' => 30710.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'groupId' => 22,
                'brandId' => 5,
                'barcode' => '1234567890127',
                'name' => 'GeForce RTX 4060 8GB Dual EVO OC Edition',
                'website' => 'https://www.asus.com/motherboards-components/graphics-cards/dual/dual-rtx4060-o8g-evo/techspec/',
                'parameter_ids' => '42,43,44,45,46,47,48,49,50,51,52',
                'description' => '',
                'status' => 'active',
                'price' => 130590.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'groupId' => 22,
                'brandId' => 5,
                'barcode' => '1234567890128',
                'name' => 'GeForce RTX 5070 12GB TUF Gaming OC Edition',
                'website' => 'https://www.asus.com/motherboards-components/graphics-cards/tuf-gaming/tuf-rtx5070-o12g-gaming/techspec/',
                'parameter_ids' => '53,54,55,56,57,58,59,60,61',
                'description' => '',
                'status' => 'active',
                'price' => 339990.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'groupId' => 22,
                'brandId' => 11,
                'barcode' => '1234567890129',
                'name' => 'Radeon RX 7800 XT GAMING OC 16G',
                'parameter_ids' => '',
                'description' => '',
                'status' => 'active',
                'price' => 223990.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'groupId' => 22,
                'brandId' => 11,
                'barcode' => '1234567890130',
                'name' => 'GeForce RTX 4060 8GB D6 8G',
                'parameter_ids' => '',
                'description' => '',
                'status' => 'active',
                'price' => 130590.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'groupId' => 23,
                'brandId' => 2,
                'barcode' => '1234567890131',
                'name' => 'Odyssey G55T',
                'parameter_ids' => '',
                'description' => '',
                'status' => 'active',
                'price' => 136990.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'groupId' => 23,
                'brandId' => 2,
                'barcode' => '1234567890132',
                'name' => 'S3 S36GD',
                'parameter_ids' => '',
                'description' => '',
                'status' => 'active',
                'price' => 41390.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'groupId' => 23,
                'brandId' => 18,
                'barcode' => '1234567890133',
                'name' => '241E1SC/00',
                'parameter_ids' => '',
                'description' => '',
                'status' => 'active',
                'price' => 38630.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'groupId' => 23,
                'brandId' => 18,
                'barcode' => '1234567890134',
                'name' => ' 345B1C/00',
                'parameter_ids' => '',
                'description' => '',
                'status' => 'active',
                'price' => 183390.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'groupId' => 24,
                'brandId' => 2,
                'barcode' => '1234567890135',
                'name' => 'ViewFinity S8 S80D UHD',
                'parameter_ids' => '',
                'description' => '',
                'status' => 'active',
                'price' => 151640.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'groupId' => 24,
                'brandId' => 2,
                'barcode' => '1234567890136',
                'name' => 'Odyssey G7',
                'parameter_ids' => '',
                'description' => '',
                'status' => 'active',
                'price' => 224880.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'groupId' => 24,
                'brandId' => 5,
                'barcode' => '1234567890137',
                'name' => 'TUF Gaming VG34VQL3A',
                'parameter_ids' => '',
                'description' => '',
                'status' => 'active',
                'price' => 140610.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'groupId' => 24,
                'brandId' => 5,
                'barcode' => '1234567890138',
                'name' => 'PG42UQ ROG SWIFT',
                'parameter_ids' => '',
                'description' => '',
                'status' => 'active',
                'price' => 591390.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'groupId' => 25,
                'brandId' => 24,
                'barcode' => '1234567890139',
                'name' => 'DataTraveler Max',
                'parameter_ids' => '',
                'description' => '',
                'status' => 'active',
                'price' => 15690.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'groupId' => 25,
                'brandId' => 24,
                'barcode' => '1234567890140',
                'name' => 'DataTraveler Kyson',
                'parameter_ids' => '',
                'description' => '',
                'status' => 'active',
                'price' => 10640.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'groupId' => 25,
                'brandId' => 25,
                'barcode' => '1234567890141',
                'name' => 'Ultra Dual Drive GO',
                'parameter_ids' => '',
                'description' => '',
                'status' => 'active',
                'price' => 10820.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'groupId' => 25,
                'brandId' => 25,
                'barcode' => '1234567890142',
                'name' => 'Cruzer Blade',
                'parameter_ids' => '',
                'description' => '',
                'status' => 'active',
                'price' => 5690.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],

            [
                'groupId' => 26,
                'brandId' => 24,
                'barcode' => '1234567890143',
                'name' => 'Canvas Select Plus CL10',
                'parameter_ids' => '',
                'description' => '',
                'status' => 'active',
                'price' => 5780.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'groupId' => 26,
                'brandId' => 24,
                'barcode' => '1234567890144',
                'name' => 'Canvas Go! Plus UHS-I U3 V30 A2 + adapter',
                'parameter_ids' => '',
                'description' => '',
                'status' => 'active',
                'price' => 9620.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'groupId' => 26,
                'brandId' => 25,
                'barcode' => '1234567890145',
                'name' => 'Extreme CL10 A2 V30 + adapter',
                'parameter_ids' => '',
                'description' => '',
                'status' => 'active',
                'price' => 10900.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'groupId' => 26,
                'brandId' => 25,
                'barcode' => '1234567890146',
                'name' => 'Ultra CL10 A1 + adapter',
                'parameter_ids' => '',
                'description' => '',
                'status' => 'active',
                'price' => 15520.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],

            [
                'groupId' => 27,
                'brandId' => 7,
                'barcode' => '1234567890147',
                'name' => 'KB216 multimedia',
                'parameter_ids' => '',
                'description' => '',
                'status' => 'active',
                'price' => 6390.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'groupId' => 27,
                'brandId' => 7,
                'barcode' => '1234567890148',
                'name' => 'KB740 Compact Multi-Device',
                'parameter_ids' => '',
                'description' => '',
                'status' => 'active',
                'price' => 24590.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'groupId' => 27,
                'brandId' => 5,
                'barcode' => '1234567890149',
                'name' => 'TUF Gaming K3 II Red switch',
                'parameter_ids' => '',
                'description' => '',
                'status' => 'active',
                'price' => 35190.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'groupId' => 27,
                'brandId' => 5,
                'barcode' => '1234567890150',
                'name' => 'ROG Azoth M701',
                'parameter_ids' => '',
                'description' => '',
                'status' => 'active',
                'price' => 88090.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],

            [
                'groupId' => 28,
                'brandId' => 10,
                'barcode' => '1234567890151',
                'name' => 'MX202',
                'parameter_ids' => '',
                'description' => '',
                'status' => 'active',
                'price' => 3990.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'groupId' => 28,
                'brandId' => 10,
                'barcode' => '1234567890152',
                'name' => 'Predator Cestus 335',
                'parameter_ids' => '',
                'description' => '',
                'status' => 'active',
                'price' => 35550.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'groupId' => 28,
                'brandId' => 7,
                'barcode' => '1234567890153',
                'name' => 'Mobile Pro MS5120W',
                'parameter_ids' => '',
                'description' => '',
                'status' => 'active',
                'price' => 10990.00,
                'discount' => 10.00,
                'unit' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],

        ];

        foreach ($items as $item) {
            DB::table('items')->insert(array_merge($item, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
