<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class ItemgroupSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('itemgroups')->insert([
            [
                'id' => 1,
                'position' => 1,
                'name' => 'Számítástechnika',
                'status' => 'active',
                'level' => 1,
                'parent_id' => 0,
                'image_path' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'position' => 2,
                'name' => 'Mobil, Tablet',
                'status' => 'active',
                'level' => 1,
                'parent_id' => 0,
                'image_path' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'position' => 3,
                'name' => 'Háztartási nagygépek',
                'status' => 'active',
                'level' => 1,
                'parent_id' => 0,
                'image_path' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'position' => 4,
                'name' => 'Otthon',
                'status' => 'active',
                'level' => 1,
                'parent_id' => 0,
                'image_path' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'position' => 5,
                'name' => 'Kert, Barkács',
                'status' => 'active',
                'level' => 1,
                'parent_id' => 0,
                'image_path' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'position' => 6,
                'name' => 'Világítás',
                'status' => 'active',
                'level' => 1,
                'parent_id' => 0,
                'image_path' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'position' => 7,
                'name' => "Játék",
                "status" =>'active',
                 "level" =>'1',
                 "parent_id" =>'0',
                 "image_path" =>'0',
                 "created_by" =>'1',
                 "updated_by" =>'1',
                 "created_at" => now(),
                 "updated_at" =>now(),
            ],
            [
                'id' => 8,
                'position' => 8,
                'name' => 'Autó ápolás,  -felszerelés',
                'status' => 'active',
                'level' => 1,
                'parent_id' => 0,
                'image_path' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'position' => 9,
                'name' => 'Sport, Szabadidő',
                'status' => 'active',
                'level' => 1,
                'parent_id' => 0,
                'image_path' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'position' => 10,
                'name' => "Drogéria",
                 "status" =>'active',
                 "level" =>'1',
                 "parent_id" =>'0',
                 "image_path" =>'0',
                 "created_by" =>'1',
                 "updated_by" =>'1',
                 "created_at" => now(),
                 "updated_at" =>now(),
            ],
            [
                'id' => 11,
                'position' => 1,
                'name' => 'Alkatrészek',
                'status' => 'active',
                'level' => 2,
                'parent_id' => 1,
                'image_path' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'position' => 2,
                'name' => "Monitorok",
                 "status" =>'active',
                 "level" =>'2',
                 "parent_id" =>'1',
                 "image_path" =>'0',
                 "created_by" =>'1',
                 "updated_by" =>'1',
                 "created_at" => now(),
                 "updated_at" =>now(),
            ],
            [
                'id' => 13,
                'position' => 3,
                'name' => "Adathordozók",
                 "status" =>'active',
                 "level" =>'2',
                 "parent_id" =>'1',
                 "image_path" =>'0',
                 "created_by" =>'1',
                 "updated_by" =>'1',
                 "created_at" => now(),
                 "updated_at" =>now(),
            ],
            [
                'id' => 14,
                'position' => 4,
                'name' => "Perifériák",
                 "status" =>'active',
                 "level" =>'2',
                 "parent_id" =>'1',
                 "image_path" =>'0',
                 "created_by" =>'1',
                 "updated_by" =>'1',
                 "created_at" => now(),
                 "updated_at" =>now(),
            ],
            [
                'id' => 15,
                'position' => 1,
                'name' => "Mobiltelefonok",
                 "status" =>'active',
                 "level" =>'2',
                 "parent_id" =>'2',
                 "image_path" =>'0',
                 "created_by" =>'1',
                 "updated_by" =>'1',
                 "created_at" => now(),
                 "updated_at" =>now(),
            ],
            [
                'id' => 16,
                'position' => 2,
                'name' => "Tabletek",
                 "status" =>'active',
                 "level" =>'2',
                 "parent_id" =>'2',
                 "image_path" =>'0',
                 "created_by" =>'1',
                 "updated_by" =>'1',
                 "created_at" => now(),
                 "updated_at" =>now(),
            ],
            [
                'id' => 17,
                'position' => 1,
                'name' => "E-book olvasók",
                 "status" =>'active',
                 "level" =>'2',
                 "parent_id" =>'2',
                 "image_path" =>'0',
                 "created_by" =>'1',
                 "updated_by" =>'1',
                 "created_at" => now(),
                 "updated_at" =>now(),
            ],
            [
                'id' => 18,
                'position' => 1,
                'name' => "Mosógépek",
                 "status" =>'active',
                 "level" =>'2',
                 "parent_id" =>'3',
                 "image_path" =>'0',
                 "created_by" =>'1',
                 "updated_by" =>'1',
                 "created_at" => now(),
                 "updated_at" =>now(),
            ],
            [
                'id' => 19,
                'position' => 2,
                'name' => "Hűtők",
                 "status" =>'active',
                 "level" =>'2',
                 "parent_id" =>'3',
                 "image_path" =>'0',
                 "created_by" =>'1',
                 "updated_by" =>'1',
                 "created_at" => now(),
                 "updated_at" =>now(),
            ],
            [
                'id' => 20,
                'position' => 3,
                'name' => "Mosogatógépek",
                 "status" =>'active',
                 "level" =>'2',
                 "parent_id" =>'3',
                 "image_path" =>'0',
                 "created_by" =>'1',
                 "updated_by" =>'1',
                 "created_at" => now(),
                 "updated_at" =>now(),
            ],
            [
                'id' => 21,
                'position' => 1,
                'name' => "Alaplapok",
                 "status" =>'active',
                 "level" =>'3',
                 "parent_id" =>'11',
                 "image_path" =>'0',
                 "created_by" =>'1',
                 "updated_by" =>'1',
                 "created_at" => now(),
                 "updated_at" =>now(),
            ],
            [
                'id' => 22,
                'position' => 2,
                'name' => "Videokártyák",
                 "status" =>'active',
                 "level" =>'3',
                 "parent_id" =>'11',
                 "image_path" =>'0',
                 "created_by" =>'1',
                 "updated_by" =>'1',
                 "created_at" => now(),
                 "updated_at" =>now(),
            ],
            [
                'id' => 23,
                'position' => 1,
                'name' => "Ívelt monitorok",
                 "status" =>'active',
                 "level" =>'3',
                 "parent_id" =>'12',
                 "image_path" =>'0',
                 "created_by" =>'1',
                 "updated_by" =>'1',
                 "created_at" => now(),
                 "updated_at" =>now(),
            ],
            [
                'id' => 24,
                'position' => 2,
                'name' => "4K monitorok",
                 "status" =>'active',
                 "level" =>'3',
                 "parent_id" =>'12',
                 "image_path" =>'0',
                 "created_by" =>'1',
                 "updated_by" =>'1',
                 "created_at" => now(),
                 "updated_at" =>now(),
            ],
            [
                'id' => 25,
                'position' => 1,
                'name' => "Pendrive",
                 "status" =>'active',
                 "level" =>'3',
                 "parent_id" =>'13',
                 "image_path" =>'0',
                 "created_by" =>'1',
                 "updated_by" =>'1',
                 "created_at" => now(),
                 "updated_at" =>now(),
            ],
            [
                'id' => 26,
                'position' => 2,
                'name' => "Memóriakártyák",
                 "status" =>'active',
                 "level" =>'3',
                 "parent_id" =>'13',
                 "image_path" =>'0',
                 "created_by" =>'1',
                 "updated_by" =>'1',
                 "created_at" => now(),
                 "updated_at" =>now(),
            ],
            [
                'id' => 27,
                'position' => 1,
                'name' => "Billentyűzetek",
                 "status" =>'active',
                 "level" =>'3',
                 "parent_id" =>'14',
                 "image_path" =>'0',
                 "created_by" =>'1',
                 "updated_by" =>'1',
                 "created_at" => now(),
                 "updated_at" =>now(),
            ],
            [
                'id' => 28,
                'position' => 2,
                'name' => "Egerek",
                 "status" =>'active',
                 "level" =>'3',
                 "parent_id" =>'14',
                 "image_path" =>'0',
                 "created_by" =>'1',
                 "updated_by" =>'1',
                 "created_at" => now(),
                 "updated_at" =>now(),
            ],
            [
                'id' => 29,
                'position' => 1,
                'name' => "iPhone",
                 "status" =>'active',
                 "level" =>'3',
                 "parent_id" =>'15',
                 "image_path" =>'0',
                 "created_by" =>'1',
                 "updated_by" =>'1',
                 "created_at" => now(),
                 "updated_at" =>now(),
            ],
            [
                'id' => 30,
                'position' => 2,
                'name' => "Samsung",
                 "status" =>'active',
                 "level" =>'3',
                 "parent_id" =>'15',
                 "image_path" =>'0',
                 "created_by" =>'1',
                 "updated_by" =>'1',
                 "created_at" => now(),
                 "updated_at" =>now(),
            ],
            [
                'id' => 31,
                'position' => 1,
                'name' => "iPhone",
                 "status" =>'active',
                 "level" =>'3',
                 "parent_id" =>'16',
                 "image_path" =>'0',
                 "created_by" =>'1',
                 "updated_by" =>'1',
                 "created_at" => now(),
                 "updated_at" =>now(),
            ],
            [
                'id' => 32,
                'position' => 2,
                'name' => "Samsung",
                 "status" =>'active',
                 "level" =>'3',
                 "parent_id" =>'16',
                 "image_path" =>'0',
                 "created_by" =>'1',
                 "updated_by" =>'1',
                 "created_at" => now(),
                 "updated_at" =>now(),
            ],
            [
                'id' => 33,
                'position' => 1,
                'name' => "Felültöltős",
                 "status" =>'active',
                 "level" =>'3',
                 "parent_id" =>'18',
                 "image_path" =>'0',
                 "created_by" =>'1',
                 "updated_by" =>'1',
                 "created_at" => now(),
                 "updated_at" =>now(),
            ],
            [
                'id' => 34,
                'position' => 2,
                'name' => "Elöltöltős",
                 "status" =>'active',
                 "level" =>'3',
                 "parent_id" =>'18',
                 "image_path" =>'0',
                 "created_by" =>'1',
                 "updated_by" =>'1',
                 "created_at" => now(),
                 "updated_at" =>now(),
            ],
            [
                'id' => 35,
                'position' => 1,
                'name' => "Kombinált",
                 "status" =>'active',
                 "level" =>'3',
                 "parent_id" =>'19',
                 "image_path" =>'0',
                 "created_by" =>'1',
                 "updated_by" =>'1',
                 "created_at" => now(),
                 "updated_at" =>now(),
            ],
            [
                'id' => 36,
                'position' => 2,
                'name' => "Side by side",
                 "status" =>'active',
                 "level" =>'3',
                 "parent_id" =>'19',
                 "image_path" =>'0',
                 "created_by" =>'1',
                 "updated_by" =>'1',
                 "created_at" => now(),
                 "updated_at" =>now(),
            ],
            [
                'id' => 37,
                'position' => 1,
                'name' => "Szabadon álló",
                 "status" =>'active',
                 "level" =>'3',
                 "parent_id" =>'20',
                 "image_path" =>'0',
                 "created_by" =>'1',
                 "updated_by" =>'1',
                 "created_at" => now(),
                 "updated_at" =>now(),
            ],
            [
                'id' => 38,
                'position' => 2,
                'name' => "Beépíthető",
                 "status" =>'active',
                 "level" =>'3',
                 "parent_id" =>'20',
                 "image_path" =>'0',
                 "created_by" =>'1',
                 "updated_by" =>'1',
                 "created_at" => now(),
                 "updated_at" =>now(),
            ],

        ]);
    }
}

